import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Loader2, Lock, Trash2, UserPlus } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { getTeam, inviteTeammate, removeTeammate } from "@/lib/teams.functions";

/** Studio seats and shared report library membership. */
export function TeamManager() {
  const queryClient = useQueryClient();
  const fetchTeam = useServerFn(getTeam);
  const invite = useServerFn(inviteTeammate);
  const remove = useServerFn(removeTeammate);
  const [email, setEmail] = useState("");

  const { data, isLoading } = useQuery({ queryKey: ["team"], queryFn: () => fetchTeam() });

  const inviteMutation = useMutation({
    mutationFn: (value: string) => invite({ data: { email: value } }),
    onSuccess: () => {
      toast.success("Teammate invited — they join when they sign in with that email.");
      setEmail("");
      queryClient.invalidateQueries({ queryKey: ["team"] });
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const removeMutation = useMutation({
    mutationFn: (id: string) => remove({ data: { id } }),
    onSuccess: () => {
      toast.success("Teammate removed");
      queryClient.invalidateQueries({ queryKey: ["team"] });
    },
    onError: (e: Error) => toast.error(e.message),
  });

  return (
    <section id="team" className="mt-12 scroll-mt-24">
      <h2 className="text-xl font-semibold">Team & shared library</h2>
      <Card className="mt-4 gap-4 border-border bg-surface p-6">
        {isLoading ? (
          <p className="text-sm text-muted-foreground">Loading your workspace…</p>
        ) : !data?.enabled ? (
          <div className="flex flex-col items-start gap-3">
            <Lock className="h-5 w-5 text-primary" />
            <p className="text-sm text-muted-foreground">
              Team seats and the shared report library are part of the Studio plan — 5 seats
              included, with every report visible to the whole team.
            </p>
            <Button asChild>
              <Link to="/account" hash="billing">
                Upgrade to Studio
              </Link>
            </Button>
          </div>
        ) : (
          <>
            <p className="text-sm text-muted-foreground">
              {data.seatsUsed} of {data.seats} seats used. Everyone on the team can read every
              report generated by the workspace owner.
            </p>

            {data.isOwner ? (
              <form
                className="flex flex-wrap gap-2"
                onSubmit={(e) => {
                  e.preventDefault();
                  if (email.trim()) inviteMutation.mutate(email.trim());
                }}
              >
                <Input
                  type="email"
                  value={email}
                  placeholder="teammate@studio.com"
                  onChange={(e) => setEmail(e.target.value)}
                  className="max-w-xs"
                />
                <Button type="submit" disabled={inviteMutation.isPending}>
                  {inviteMutation.isPending ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : (
                    <UserPlus className="h-4 w-4" />
                  )}
                  Invite
                </Button>
              </form>
            ) : null}

            <div className="divide-y divide-border border-t border-border">
              {data.members.length === 0 ? (
                <p className="pt-4 text-sm text-muted-foreground">No teammates yet.</p>
              ) : (
                data.members.map((m) => (
                  <div key={m.id} className="flex items-center justify-between gap-3 py-3">
                    <div className="min-w-0">
                      <p className="truncate text-sm">{m.invited_email}</p>
                      <p className="font-mono text-xs text-muted-foreground">
                        {m.joined_at ? "Joined" : "Invited — pending first sign-in"}
                      </p>
                    </div>
                    {data.isOwner ? (
                      <Button
                        variant="ghost"
                        size="icon"
                        aria-label="Remove teammate"
                        disabled={removeMutation.isPending}
                        onClick={() => removeMutation.mutate(m.id)}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    ) : null}
                  </div>
                ))
              )}
            </div>
          </>
        )}
      </Card>
    </section>
  );
}
